import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Darker",
  description: "Generated by create next app",
  icons: {
    icon: "../app/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(raleway.className, "antialiased")}>
        {children}
      </body>
    </html>
  );
}
